### ISSUE TITLE
[Umbrella] Automating various meetup operational tasks

### ISSUE THREAD

**Issue by girikuncoro** [cloudnative-id/meetups#4]
This is intended to be umbrella issue to automate and make organizing meetups more fun. This is called MeetOps, DevOps to autoscale meetups and communities in Indonesia. Feel free to add any ideas that can automate literally anything in running meetup groups, creating events, teaching workshops, etc.

I'll start with my ideas:
_Refering to [MVP Checklist](https://github.com/cloudnative-id/meetups/blob/master/.github/ISSUE_TEMPLATE/create-meetup-event.md) when creating meetup event, this is what we can automate_:
- [ ] Generate meetup event description/agenda (based on [this template](https://github.com/cloudnative-id/meetups/blob/master/MEETUP_DESCRIPTION.md))
- [ ] Call Meetup API to create event description, review then announce (refer to [Meetup.com API docs](https://www.meetup.com/meetup_api/))
- [x] Generate poster template for each meetup group using [artwork generator](https://github.com/cloudnative-id/artwork/tree/master/poster/generator)
- [ ] Generate creating content for welcoming and community update slide using [Google slide api](https://developers.google.com/slides)
- [ ] Since we generally collect speaker info through google form, make use of [Google form API](https://developers.google.com/apps-script/reference/forms) to populate speaker info in poster, slides, meetup.com page
- [ ] 🏃‍♂️Generate bit.ly link for our meetup event using [bitly API](https://dev.bitly.com/) @2pai
- [ ] Easy setup of OBS streaming (i.e. single click of [the manual steps](https://github.com/cloudnative-id/meetups/blob/master/RECORDING_MEETUP_EVENT.md))
- [ ] Generate twitter & telegram post automation for each related events.

**Comment by irvifa** [comment]
Hi all 👋 l, I think generate twitter post automation for each related events will be necessary since we need publication for the events. 

```
curl -XPOST 
  --url 'https://api.twitter.com/1.1/statuses/update.json?status=hello' 
  --header 'authorization: OAuth
  oauth_consumer_key="oauth_customer_key",
  oauth_nonce="generated_oauth_nonce",
  oauth_signature="generated_oauth_signature",
  oauth_signature_method="HMAC-SHA1",
  oauth_timestamp="generated_timestamp",
  oauth_token="oauth_token",
  oauth_version="1.0"'
```

Ref:
https://help.twitter.com/en/rules-and-policies/twitter-automation
https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update

**Comment by girikuncoro** [comment]
We should gather feedback regularly from meetup so that we can improve. Creation of feedback forrm and QR code can be automated.

**Comment by zufardhiyaulhaq** [comment]
I want to ask to clear our understanding of how to automating the MeetOps:
- As a meetup organizer, how I start the automation tools to run? are just by editing meetup.yaml file in a specific city directory?
- Are we using CI like GitHub actions? or using a mechanism like kubeweekly?
- I think we can use the same mechanism as kubeweekly and separate the tasks in a cronjob and adding some field into the YAML file, so all database is store in git.
![code](https://user-images.githubusercontent.com/11990726/71558680-6ebcb080-2a88-11ea-9b54-e9922b026807.png)
- `status` field defines how each specific program (generate poster, create meetup page, etc) should run or not.

**Comment by 2pai** [comment]
HI , I'm taking ```Generate bit.ly link ```

**Comment by girikuncoro** [comment]
@2pai I have created separate issue for bit.ly: https://github.com/cloudnative-id/meetups/issues/26

**Comment by girikuncoro** [comment]
@zufardhiyaulhaq that's a really nice idea! we can attach list of tasks to each meetup for executing the tasklist everytime a meetup is created. for now we can get ready with the "building blocks" tool before stitching them together as fully automated setup

for this idea to work, we need to implement bot that can commit changes to git repo for us first

**Comment by zufardhiyaulhaq** [comment]
I am taking the `Announcer System`. Based on the discussion on Telegram, We agree to use this system:
![photo_2019-12-24_15-21-12](https://user-images.githubusercontent.com/11990726/72004886-ef489180-327e-11ea-9109-d6fe6789670c.jpg)

I want to ask to clear our understanding:
- Should the content service (include kubeweekly) run as a cronjob?
- Is announcer orchestrator running as a background service, which means deployed into Pod and continuously pulls & checks data from Git Repo?
- Should we split dispatcher from orchestrator?

**Comment by zufardhiyaulhaq** [comment]
Update:
- MVP for the announcer system is available in https://github.com/cloudnative-id/announcer-system.

**Comment by zufardhiyaulhaq** [comment]
Hi all, I have an update announcer system to be able to post new meetups into Telegram
https://github.com/cloudnative-id/announcer-system

How to:
- update ContentList.yaml under `resources/meetup` (follow example bandung4)
- create new files named `{CITY}{MEETUP_NUMBER}` in `resources/meetup/contents` (follow example `bandung4.yaml`)
- upload poster named `{CITY}{MEETUP_NUMBER}` in `resources/meetup/contents/picture` (follow example `bandung4.jpg`)
- enjoy

You must do manually until meetup automation is complete (generate poster, etc).
